package com.spyou.youtubedownload.ui.theme

import androidx.compose.ui.graphics.Color

// Light Theme Colors — Clean blue/grey palette
val md_theme_light_primary = Color(0xFF1A73E8)
val md_theme_light_onPrimary = Color(0xFFFFFFFF)
val md_theme_light_primaryContainer = Color(0xFFD2E3FC)
val md_theme_light_onPrimaryContainer = Color(0xFF001D36)
val md_theme_light_secondary = Color(0xFF5F6368)
val md_theme_light_onSecondary = Color(0xFFFFFFFF)
val md_theme_light_secondaryContainer = Color(0xFFE8EAED)
val md_theme_light_onSecondaryContainer = Color(0xFF1F1F1F)
val md_theme_light_tertiary = Color(0xFF1A73E8)
val md_theme_light_onTertiary = Color(0xFFFFFFFF)
val md_theme_light_tertiaryContainer = Color(0xFFD2E3FC)
val md_theme_light_onTertiaryContainer = Color(0xFF001D36)
val md_theme_light_error = Color(0xFFD93025)
val md_theme_light_onError = Color(0xFFFFFFFF)
val md_theme_light_errorContainer = Color(0xFFFCE8E6)
val md_theme_light_onErrorContainer = Color(0xFF410E0B)
val md_theme_light_outline = Color(0xFF80868B)
val md_theme_light_background = Color(0xFFFAFAFA)
val md_theme_light_onBackground = Color(0xFF202124)
val md_theme_light_surface = Color(0xFFFAFAFA)
val md_theme_light_onSurface = Color(0xFF202124)
val md_theme_light_surfaceVariant = Color(0xFFF1F3F4)
val md_theme_light_onSurfaceVariant = Color(0xFF5F6368)
val md_theme_light_inverseSurface = Color(0xFF303134)
val md_theme_light_inverseOnSurface = Color(0xFFF1F3F4)
val md_theme_light_inversePrimary = Color(0xFF8AB4F8)
val md_theme_light_surfaceTint = Color(0xFF1A73E8)
val md_theme_light_outlineVariant = Color(0xFFDADCE0)
val md_theme_light_scrim = Color(0xFF000000)

// Dark Theme Colors — Spotify-inspired dark with soft blue accents
val md_theme_dark_primary = Color(0xFF8AB4F8)
val md_theme_dark_onPrimary = Color(0xFF003062)
val md_theme_dark_primaryContainer = Color(0xFF1A5276)
val md_theme_dark_onPrimaryContainer = Color(0xFFD2E3FC)
val md_theme_dark_secondary = Color(0xFFBDC1C6)
val md_theme_dark_onSecondary = Color(0xFF303134)
val md_theme_dark_secondaryContainer = Color(0xFF3C4043)
val md_theme_dark_onSecondaryContainer = Color(0xFFE8EAED)
val md_theme_dark_tertiary = Color(0xFF8AB4F8)
val md_theme_dark_onTertiary = Color(0xFF003062)
val md_theme_dark_tertiaryContainer = Color(0xFF1A5276)
val md_theme_dark_onTertiaryContainer = Color(0xFFD2E3FC)
val md_theme_dark_error = Color(0xFFF28B82)
val md_theme_dark_onError = Color(0xFF601410)
val md_theme_dark_errorContainer = Color(0xFF8C1D18)
val md_theme_dark_onErrorContainer = Color(0xFFFCE8E6)
val md_theme_dark_outline = Color(0xFF5F6368)
val md_theme_dark_background = Color(0xFF121212)
val md_theme_dark_onBackground = Color(0xFFE8EAED)
val md_theme_dark_surface = Color(0xFF121212)
val md_theme_dark_onSurface = Color(0xFFE8EAED)
val md_theme_dark_surfaceVariant = Color(0xFF2D2D2D)
val md_theme_dark_onSurfaceVariant = Color(0xFFBDC1C6)
val md_theme_dark_inverseSurface = Color(0xFFE8EAED)
val md_theme_dark_inverseOnSurface = Color(0xFF303134)
val md_theme_dark_inversePrimary = Color(0xFF1A73E8)
val md_theme_dark_surfaceTint = Color(0xFF8AB4F8)
val md_theme_dark_outlineVariant = Color(0xFF3C4043)
val md_theme_dark_scrim = Color(0xFF000000)

// YouTube Brand Colors
val YouTubeRed = Color(0xFFFF0000)
val YouTubeRedDark = Color(0xFFCC0000)
val SuccessGreen = Color(0xFF34A853)
val WarningOrange = Color(0xFFFBBC04)
